export type { User, UserRole, UserStatus, Gender, Role, Permission, RolePermission, UserRoleMembership } from "./entities/user";
export { ROLE_PERMISSIONS, PERMISSION_DOMAINS, ROLE_DESCRIPTIONS } from "./entities/user";
export type { StudentProfile } from "./entities/student";
export type { ParentProfile, ParentChildLink } from "./entities/parent";
export type { StaffProfile, StaffStatus } from "./entities/staff";
export type { AdmissionStatus } from "./entities/admission";
export type { Subject, Topic, Lesson, Exercise } from "./entities/subject";
export type { Course, Module, Unit, CourseEnrollment, CourseStatus } from "./entities/course";
export type { Class, Enrollment, ClassSchedule } from "./entities/academics";
export type { AttendanceRecord, AttendanceStatus } from "./entities/attendance";
export type { Assignment, Submission, SubmissionStatus } from "./entities/assignment";
export type { Exam, ExamSchedule, ExamResult } from "./entities/exam";
export type { Grade, GradeBook, GradeScale } from "./entities/grade";
export type { FinanceTransaction, FinanceTransactionType, FinanceTransactionStatus } from "./entities/finance";
export type { Expense, ExpenseStatus } from "./entities/expense";
export type { PayrollRecord, PayrollStatus } from "./entities/payroll";
export type { TransportRoute, Vehicle, Stop, StudentTransportAssignment } from "./entities/transport";
export type { Book, BookCopy, Borrowing } from "./entities/library";
export type { InventoryItem } from "./entities/inventory";
export type { Notification, NotificationChannel, NotificationPriority } from "./entities/notification";
export type { Document, DocumentType } from "./entities/document";
export type { AuditLog } from "./entities/audit";
export type { CalendarEvent, CalendarEventType } from "./entities/calendar";
export type { Invitation, InvitationStatus } from "./entities/invitation";
export type { SystemSetting } from "./entities/system";
export type { ApiResponse, PaginatedResponse, PaginationMeta } from "./api";
export type { AuthTokens, AuthUser } from "./auth";
